[phases.setup]
nixPkgs = ["jdk11"]

[phases.build]
cmds = ["javac --release 11 -Xlint:deprecation -cp \"libs/*\" backend/ChatBotServer.java"]

[start]
cmd = "java -cp \".:libs/*\" backend.ChatBotServer"
